---
- name: Preparing hosts
  hosts: all
  tasks:

    - name: Edit /etc/profile
      become: true
      ansible.builtin.blockinfile:
        path: /etc/profile
        block: |
          shopt -s histappend
          export HISTSIZE=10000
          export HISTTIMEFORMAT="%h %d %H:%M:%S "
          PROMPT_COMMAND='history -a'
          export HISTIGNORE="ls:ll:history:w:htop:pwd"

    - name: Update repository && upgrade packages
      become: true
      ansible.builtin.apt:
        name: "*"
        state: present
        update_cache: true

    - name: Install Packages
      become: true
      ansible.builtin.apt:
        pkg:
          - fontconfig
          - openjdk-11-jre
          - gnupg
          - gnupg2
        state: present

    - name: Rename Hostnames
      become: true
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Add user
      become: true
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /bin/bash
        home: /var/lib/jenkins

    - name: Create directory
      become: true
      ansible.builtin.file:
        path: "{{ directory }}"
        state: directory
        mode: '0755'
        owner: "{{ username }}"
        group: "{{ usergroup }}"


- name: Jenkins Installation
  hosts: master
  tasks:

    - name: Install repo key
      become: true
      ansible.builtin.apt_key:
        url: "https://pkg.jenkins.io/debian-stable/jenkins.io.key"
        state: present

    - name: Add Jenkins repo
      become: true
      ansible.builtin.apt_repository:
        repo: "deb https://pkg.jenkins.io/debian-stable binary/"
        state: present
        filename: jenkins
        update_cache: true

    - name: Install Jenkins
      become: true
      ansible.builtin.apt:
        pkg:
          - jenkins
          - git
        state: present

    - name: Start Jenkins
      ansible.builtin.systemd:
        name: jenkins
        enabled: true
        state: started

    - name: Genereate SSH Key on Master
      become: true
      ansible.builtin.user:
        name: "{{ username }}"
        generate_ssh_key: true
        ssh_key_bits: 2048
        ssh_key_file: /var/lib/jenkins/.ssh/id_rsa
      register: ssh_key_info

    - name: Edit known_hosts file
      become: true
      become_user: jenkins
      ansible.builtin.known_hosts:
        name: "{{ hostvars[item].ansible_host }}"
        state: present
        key: "{{ lookup('pipe', 'ssh-keyscan {{ hostvars[item].ansible_host }}') }}"
        hash_host: true
        path: /var/lib/jenkins/.ssh/known_hosts
      with_items:
        - agent


- name: Jenkins Agent Configuration
  hosts: agent
  tasks:

    - name: Add master publickey
      become: true
      ansible.posix.authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ hostvars['master']['ssh_key_info']['ssh_public_key'] }}"

    - name: Install Packages
      become: true
      ansible.builtin.apt:
        pkg:
          - git
          - python3-pip
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Upgrade pip
      become: true
      become_user: "{{ username }}"
      ansible.builtin.pip:
        name: pip
        state: present
        executable: pip3
        extra_args: '--upgrade'
      vars:
        ansible_python_interpreter: /usr/bin/python3.7

    - name: Install Ansible
      become: true
      become_user: "{{ username }}"
      ansible.builtin.pip:
        name:
          - ansible
          - ansible-lint<6.0
          - molecule==3.4.0
          - molecule_docker
          - docker
          - yamllint
        state: present
        executable: pip3
      vars:
        ansible_python_interpreter: /usr/bin/python3.7

    - name: Install Docker repo key
      become: true
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/debian/gpg"
        state: present

    - name: Add Docker repo
      become: true
      ansible.builtin.apt_repository:
        repo: "deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        filename: docker
        state: present
        update_cache: true

    - name: Install Docker
      become: true
      ansible.builtin.apt:
        pkg:
          - docker-ce
        state: present

    - name: Add jenkins user to docker group
      become: true
      ansible.builtin.user:
        name: "{{ username }}"
        groups: docker

    - name: Restart docker
      become: true
      ansible.builtin.systemd:
        name: docker
        state: restarted
        enabled: true

    - name: Install agent.jar
      become: true
      ansible.builtin.get_url:
        url: "http://{{ hostvars['master']['ansible_host'] }}:8080/jnlpJars/agent.jar"
        dest: "{{ directory }}"
        mode: '0644'
      register: install_agent
      until: install_agent is succeeded
      retries: 10
      timeout: 10

- name: Jenkins Configuration
  hosts: master
  tasks:

    - name: Wait 20 seconds
      ansible.builtin.wait_for:
        timeout: 20

    - name: Check file
      become: true
      ansible.builtin.stat:
        path: "/var/lib/jenkins/secrets/initialAdminPassword"
      register: script

    - name: Init admin password
      become: true
      ansible.builtin.command: "cat /var/lib/jenkins/secrets/initialAdminPassword"
      changed_when: false
      register: result
      when: script.stat.exists

    - name: Print admin password
      ansible.builtin.debug:
        var: result.stdout
      when: script.stat.exists
...
