---
- name: Jenkins Provisioning
  hosts: all
  tasks:

- name: Jenkins Provisioning | Debian
  ansible.builtin.import_playbook: debian.yml
  when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution_major_version'] == "10"
  tags: [always]

- name: Jenkins Provisioning | CentOS7
  ansible.builtin.import_playbook: rhel.yml
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"
  tags: [always]
...
